FROM python:3.6-bullseye

RUN apt-get update && apt-get install -y redis
RUN python3 -m pip install mockito coverage

COPY . /opt/minqlx-plugins
WORKDIR /opt/minqlx-plugins

RUN python3 -m pip install -r requirements.txt
CMD ["./tests/dockerfiles/entrypoint.sh"]
