jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10", "3.9", "3.8", "3.7"]
        os: ["ubuntu-22.04"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Include ppa repository
        run: sudo add-apt-repository ppa:deadsnakes/ppa
      - name: Set up Python ${{ matrix.python-version }}
        run: |
          sudo apt-get install python${{ matrix.python-version }}-dev
          sudo update-alternatives --install /usr/bin/python3 python3 `which python${{ matrix.python-version }}` 1
          sudo update-alternatives --install /usr/bin/python3-config python3-config `which python${{ matrix.python-version }}-config` 1
      - name: Install requirements for testing
        run: sudo python3 -m pip install mockito
      - name: Run tests
        run: python3 -m unittest tests
